spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 12341k
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

indexing-settings:
  sites:
    - url: https://volochek.life/
      name: Volochek
    - url: https://sendel.ru/
      name: Sendel
